kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: <namespace>
  name: <user>.snaproute.io
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role-binding-for-<user>
  namespace: <namespace>
subjects:
  - kind: User
    name: "oidc:<user>@snaproute.com"
    namespace: <namespace>
roleRef:
  kind: Role
  name: <user>.snaproute.io
  apiGroup: rbac.authorization.k8s.io
---
