apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: metallb-config
data:
  config: |
    peers:
    - peer-address: 192.168.100.1
      peer-asn: 65500
      my-asn: 65501
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.25.64.0/18
      auto-assign: false
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
        communities:
        - no-advertise
      - aggregation-length: 18
    - name: vm-pool
      protocol: bgp
      addresses:
      - 10.25.0.0/18
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
        communities:
        - no-advertise
      - aggregation-length: 18
    bgp-communities:
      no-advertise: 65535:65282
